### ISSUE TITLE
add mechanism for marking features as deprecated

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#1058]
Feature manifests should accept a boolean `"deprecated"` property.

When this value is `true`, it should be hidden in the control panel, unless:
- the feature is currently enabled, or
- any of the feature's preferences have values present in storage

This will have the effect of making the feature unavailable only to users who have never used the feature on their current installation.

Timestamps should be the first feature to be deprecated.

**Comment by marcustyphoon** [comment]
Inconsistency: script preferences are only saved to storage when you change them. Thus, this will behave differently if a user:

- Enables Timestamps
- [some time passes]
- Updates to an XKit Rewritten version in which Timestamps is deprecated
- Disables Timestamps

or if the user instead:

- Enables Timestamps
- Toggles a checkbox, decides they don't like it, toggles it back
- [some time passes]
- Updates to an XKit Rewritten version in which Timestamps is deprecated
- Disables Timestamps

In the first case, Timestamps will vanish from the preference pane even though the user has used it before and very well might have been using it minutes ago.

This could be solved by pushing a version that stores, I dunno, a `hasEverBeenEnabledScripts` array, waiting a bit, and then pushing the deprecation feature.

**Comment by AprilSylph** [comment]
Ah damn, I forgot that scripts don't save their defaults to storage on first usage anymore.

I don't think this inconsistency super matters though. Ultimately the goal is to phase the feature out of use, and conditionally continuing to provide access to it is primarily just a way to not "break" existing setups.

If anything, to resolve this inconsistency, I would rather go harder into hiding the feature(s) and ignore the presence of preferences entirely.

**Comment by marcustyphoon** [comment]
I do think ignoring preferences makes sense. (I was going to say something about, like, "what if we someday deprecate quick tags; I don't want users to lose access to their tag bundle data," but since we export preferences to JSON I actually have no qualms about that.)

I also think that disabling a script, dismissing the preference popup, opening the popup, and having that script no longer there feels a little... the kind of thing I would write a GitHub issue about. I hold this opinion very loosely, especially because it's Timestamps and who cares, but I pushed a version of #1190 that shows disabled deprecated scripts if and only if only if the user had them enabled at the moment of deprecation; that seems like a possibility to me.
