### ISSUE TITLE
Add a link to the previous post in a reblog chain

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [AprilSylph/XKit-Rewritten#1077]
### Concept

Previously, Tumblr's "X reblogged Y" header included a link to Y's post which was reblodded. Tumblr's latest update removed this, changing it to the link to Y's blog instead. Not sure whether this should be under i.e. Tweaks, or if it should be an entire new feature (so that if Tumblr officially adds it back, it can be removed/deprecated, c.f.  #1058).

**Comment by nightpool** [comment]
We will probably not do this until Tumblr makes it clear this isn't a bug. This is almost certainly a bug that Tumblr will fix in the next ~week

**Comment by DizzyHSlightlyVoided** [comment]
That is *very* fair.

**Comment by nloncar** [comment]
https://www.tumblr.com/changes/718768407758225408/tuesday-may-30th-2023
they confirmed it wasn't a bug 😒

**Comment by Laulajatar** [comment]
They now also removed the link to the current post from the poster's name, linking it only to their blog.

At the moment, there is no more way to open a post in a new tab/window (as the header cannot be right/middle clicked), and also no way to see it in the custom theme blog view at all. Every link that exists on dash, including copy link, has the tumblr.com/blogname format. The only way to find blogname.tumblr links is by going to the blog's main page and digging.

This is even worse if you view a blog in this overlay dash view, as clicking on a post will replace that window, making you lose your position since page numbers are not part of the url when you browse. 

I understand waiting for them to possibly revert it (or make more changes), but my hopes are rather low. If they don't, would this be a new issue, or belong to this one as restoring the functionality of the old post headers?

**Comment by krc** [comment]
The timestamp in the meatball menu links to the subdomain/custom theme version still (terrible place to be sure, and who knows if/when they will notice and change it)

**Comment by katyggls** [comment]
Just adding another request for this feature. It's absolutely maddening that they've removed the ability to open a simple link to the reblog of a post. Now they've even made it hard to get to the source's specific link to a post, as well. Seems like everything you click takes you to the general page for someone's blog, which is not what I or most users want when we click on the name of the person who reblogged the post. I'm aware that clicking "on the empty space in the post header" opens up the reblogger's post in the blog dash view, but again, that's not what I want. For one thing, when I tried this it wouldn't allow me to reblog the post from any of my other blogs.
