### ISSUE TITLE
Preference pane search: highlight matching options

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1111]
### Concept

It would be neat if script options that matched the current search string were subtly visually highlighted. For example, right now when searching for the option to unsticky post avatars, I might type "sticky" into the search box, click to open the options for Tweaks... and then have to read through all of the options to find the one I'm looking for, since the search doesn't descend any further than that.

**Comment by AprilSylph** [comment]
This was on my mental to-do list (pulling in a library that would highlight matching text) but ultimately I don't care enough to do anything about it. I forget the name of the library I was eyeing now...

Anyway, yeah go ahead and PR this if you find a good library for it. Building a custom solution sounds like `src/` bloat to me.

But, I won't keep this issue open as "help wanted" due to the lack of priority ranking for issues (presently).

**Comment by marcustyphoon** [comment]
I was thinking more about highlighting the entire checkbox!
