### ISSUE TITLE
Mutual Checker does not work properly

### ISSUE THREAD

**Issue by moonflowcr** [AprilSylph/XKit-Rewritten#1117]
### Platform

Windows 10

### Browser

Chrome

### Addon version

v0.21.9

### Details

Mutual Checker works fine sometimes, but some other it doesn't. Sometimes, it doesn't work even if I have it enabled and some others, it appears on a few mutuals while it doesn't next to the username of blogs I know I'm mutuals with. It usually solves itself when I refresh the page, but I use Tumblr on desktop most of the time and I rely a lot of this feature and doing so can be annoying. Not sure if it's a bug on my side or it's something about this feature in particular, but I'd appreciate it if someone could take a look at this.

**Comment by AprilSylph** [comment]
Mutual Checker has a few restrictions which may explain your troubles:
- It caches if a blog is a mutual, and does not track follows/unfollows. So, if you open a blog that follows you and then follow that blog, that blog will not show up as a mutual until you reload the page.
- It cannot check sideblogs. Secondary blogs are not technically able to follow other blogs, so even if you know who the secondary blog belongs to, they will never appear marked as mutuals.

If you think neither of these are the cause of your problem, without any other details, there isn't really anything to look into... if you notice any particular patterns that reliably cause Mutual Checker to fail, please do detail them.

**Comment by moonflowcr** [comment]
I just realized I wasn't very specific with my issue and left a few things behind, sorry.

And yes, I meant main blog and not sideblogs but I forgot to specify that. What I meant to say is that when I scroll on my dash, sometimes, I see the Mutual Checker mark next to the username of a main blog I'm mutuals with, but then when I see the next post reblogged/made by another main blog I know I've been mutuals with for a while (I even check they still follow me in the followers page just in case they've unfollowed me, but we're still mutuals), the mark doesn't show up. Like I said, it solves itself when I refresh the page, but I find it annoying I have to do that every single time I encounter that problem.

Same thing happens when the feature doesn't work at all even if it's enabled. I don't know what's going on with that.

I feel neither of the restrictions are causing this, so I hope there are enough details now to look into it

**Comment by marcustyphoon** [comment]
Hm. Not sure how to try to reproduce it since you're just using it normally.

If I could reproduce it, the first thing I would do would be to open the developer console (Ctrl + Shift + J), go to the "network" tab, filter by "Fetch/XHR," then refresh the page with the browser refresh button and use Tumblr normally until the problem occurred. If one of the lines saying e.g. `followed_by?query=april` was red, that would indicate the network was failing; if the relevant line was missing, it would more likely be a problem with our code somehow.

**Comment by Dusk-Argentum** [comment]
Heya, I just wanted to confirm that I am also having this issue. Rather than making a new issue, I decided to tack on a comment here.
### Platform
Windows 10
### Browser
Firefox (v115.0.1 64-bit)
### Addon Version
v0.21.10
### Details
Same as the OP, except that the issue resolves itself on neither a refresh nor in a private window. The aforementioned `followed_by` does not appear anywhere in the Network tab. I first noticed this issue a few days ago (Wednesday, maybe? Some time earlier this week). The only other extension running in the private window was uBlock Origin, but even disabling that didn't resolve the issue. The issue has persisted across multiple page refreshes and even computer restarts, if that helps any.
Let me know if you'd rather I moved my additional report to a new issue for better tracking!

**Comment by matoro** [comment]
I am also observing this exact issue starting around the time this issue was opened (1-2 weeks).  Mutual Checker no longer works (does not shows the little icon even for users I know are mutuals).  I didn't see any obvious errors in the JS console but haven't looked very hard yet.  Like the above user, refreshing the page does not make a difference.  I also do not see any requests to `followed_by`.

### Platform

Linux

### Browser

Firefox (v115.0.2)

### Addon version

v0.21.10

**Comment by AprilSylph** [comment]
This issue is _not_ about when Mutual Checker stopped working en masse on the 12th; that is a separate issue that was captured as #1138 and fixed in v0.21.13.

This issue predates that Tumblr update and is about **sporadic** (not permanent) loss of function.
