### ISSUE TITLE
Restore Links Post Header Tweak not functioning

### ISSUE THREAD

**Issue by valavee** [AprilSylph/XKit-Rewritten#1139]
### Platform

Windows 11

### Browser

Firefox 115.0.2

### Addon version

0.21.10

### Details

I click on the names of users to go back to a previous reblog of the post and it appears to be no longer working. I checked for an update of the extension, I turned the option on and off, but nothing has worked so far.

**Comment by marcustyphoon** [comment]
This is fixed in v0.21.12/v0.21.13, but it takes a while for the web extension stores to approve versions for release! Stay tuned.

**Comment by citrusella** [comment]
I appear to be on the correct version of the extension (though a different version of Firefox since I'm on the ESR channel but am about one or two updates behind on it right now, at 102.11.0 as opposed to the 115 ESR version that went live earlier this month) but it's not working for me at this point, either, despite turning it off and back on and reloading and such (only thing I didn't try was restarting my whole browser but there's a specific reason I can't try that right this second).

I suppose at this point it must be some strange user error on my part...

**Comment by marcustyphoon** [comment]
I just tried it on a firefox version around there and it seemed to work. You definitely have Tweaks and the option toggled on and your extension version is shown as v0.21.13 (or v0.21.14) , yeah?


<img width="376" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/292e35e1-7e12-4419-ac60-9b6eb2a19911">

**Comment by citrusella** [comment]
Yep, extension and option enabled as in screenshot, and version 0.21.13... but I think it *was* user error because it turns out that earlier I misunderstood what the tweak did--even after reading the entire pull request that implemented it, including posts that outright said *it didn't do that* 🤦‍♀️, I thought it worked on *all* user links on a post (i.e. the ones that are attached to each reblog, to turn them into what's been transferred to \*gestures vaguely at space near name "meh, click there"\*) and not just the ones at the very top (because I did not know the similar *vague gesture* behavior had even been applied to the very top one) so I had not been checking that.

(But now that I know, I shall be leaving the specific tweak on. -_-')

Thanks for responding and sorry for cluttering the (closed) issue with a misunderstanding!
