### ISSUE TITLE
New tweak proposal: revert the new "vertical nav layout"

### ISSUE THREAD

**Issue by Cortan122** [AprilSylph/XKit-Rewritten#1149]
### Concept

Tumblr recently rolled out the new Vertical Nav Layout to a large amount of users (appears not to be the default quite yet), and lots of people, including myself, don't particularly like it. From what I can tell, this feature has been in AB testing for at least 3 weeks, and there are already other Issues here relating to it.

Would it be difficult to bring back the old layout with a Tweak, or does this require reimplementing it from scratch?

**Comment by marcustyphoon** [comment]
> From what I can tell, this feature has been in AB testing for at least 3 weeks

That I know of, the A/B testing just started today! I hadn't seen anyone post about it before a few hours ago, and people suuuuure are now :D I was able to get earlier access to it on one of my accounts as an XKit dev, though (hence why XKit isn't broken on it!)

Anyway, we generally don't do big modifications for things that are still in testing, I think; that would kind of defeat the point of the test—can't tell if people get used to the changes in the first week or two if they all revert the changes on day one—along with meaning we would have to try to ship code that works whether you're in the A group or the B group!

_(for the record, I of course have plenty of tweaks I would really make to it—I wrote support a short novel—but 3 weeks in I'm currently on team "you get used to it quickly and this seems to have more upsides than downsides")_

**Comment by AprilSylph** [comment]
> Would it be difficult to bring back the old layout with a Tweak, or does this require reimplementing it from scratch?

It would require implementing the old layout ourselves. Despite how well some Tweaks do their job, we can't literally _reverse_ updates except in very specific situations, and this isn't one of them.

**Comment by spriteatlas** [comment]
> _(for the record, I of course have plenty of tweaks I would really make to it—I wrote support a short novel—but 3 weeks in I'm currently on team "you get used to it quickly and this seems to have more upsides than downsides")_


very curious as to what "upsides" you've noticed (genuinely asking - it just rolled out for me so i havent had time to get used to it and all i've noticed is how it breaks my usual patterns on the site and that it looks bad and kind of cluttered).

**Comment by InfectedGriffon** [comment]
instead of reimplementing the entire old layout, it would probably suffice to just move the sidebars out to the edges again.

**Comment by enchanted-sword** [comment]
@AprilSylph I wrote a quick-fix userscript today that just rearranges the UI and it works pretty dang well. It's hardly a professional fix, but I managed to get all the buttons back to pretty much the same layout, give or take a dozen pixels. Since the update hasn't rolled out to everyone, I was also able to make use of some features from the old layout, such as the old navigation bar and unread post and notification icons hovering on the corner of the home and notification icons. I'm probably not the person for the job, but would be more than happy if someone wanted to integrate my fix into XKit.

**Comment by hakkitakki** [comment]
> @AprilSylph I wrote a quick-fix userscript today that just rearranges the UI and it works pretty dang well. It's hardly a professional fix, but I managed to get all the buttons back to pretty much the same layout, give or take a dozen pixels. Since the update hasn't rolled out to everyone, I was also able to make use of some features from the old layout, such as the old navigation bar and unread post and notification icons hovering on the corner of the home and notification icons. I'm probably not the person for the job, but would be more than happy if someone wanted to integrate my fix into XKit.

Would you be willing to share for people to integrate this on a personal level? The new UI doesn't scale correctly on my screen and it's driving me nuts

**Comment by enchanted-sword** [comment]
> Would you be willing to share for people to integrate this on a personal level? The new UI doesn't scale correctly on my screen and it's driving me nuts

https://github.com/enchanted-sword/dashboard-unfucker

**Comment by Daddu3** [comment]
> @AprilSylph I wrote a quick-fix userscript today that just rearranges the UI and it works pretty dang well. It's hardly a professional fix, but I managed to get all the buttons back to pretty much the same layout, give or take a dozen pixels. Since the update hasn't rolled out to everyone, I was also able to make use of some features from the old layout, such as the old navigation bar and unread post and notification icons hovering on the corner of the home and notification icons. I'm probably not the person for the job, but would be more than happy if someone wanted to integrate my fix into XKit.

I second implementing this on XKit, just tested this script and the sigh of relief I had seeing the old layout again was immense.

**Comment by enchanted-sword** [comment]
If the vertical nav layout doesn't get scrapped or become optional after the initial testing period, I'll port my fix to XKit

**Comment by enchanted-sword** [comment]
Welp.

**Comment by mayfrogs** [comment]
I just want to express that I would also like for the dashboard unfucker to be implemented into xkit if possible. I hate the new layout, it's claustrophobia inducing and overstimulating. But I already have so many firefox extensions installed—and I try to keep the number of extensions I have to a minimum in order to avoid not only bogging down my cpu but also minimizing the amount of potential backdoors for malicious activity. I really don't want to have to need more than one browser extension installed just to comfortably use tumblr. It seems like every website nowadays needs at least one extension to make it usable, and it's really starting to add up. Some consolidation would be really nice.
