### ISSUE TITLE
Restore links to individual posts in the post header broken

### ISSUE THREAD

**Issue by katyggls** [AprilSylph/XKit-Rewritten#1238]
### Platform

Windows 10

### Browser

Microsoft Edge Version 116.0.1938.54 (Official build) (64-bit)

### Addon version

v0.22.0

### Details

Restored links to individual posts in the post header under "Tweaks" is broken again in some cases. When reblogged/drafted/queued from the original poster, it just shows a blank space, and then the source appears in the reblogged post header, but it once again only goes to the front page of their blog in the blog view, and not the direct link to the original post. See screenshot for what I mean.

You can click on the blank space which brings up the post so it can be reblogged, but only from the blog you originally reblogged/drafted/queued it from. I use the drafts on some of my sideblogs to save posts I want to reblog with my main blog later, so this is definitely an issue for me, and I know other people do this as well.

Screenshot: 
![2023-08-23 09 08 39](https://github.com/AprilSylph/XKit-Rewritten/assets/13756649/86269268-9a73-44f9-bc6e-c5dfbdb70039)

**Comment by inklesspen** [comment]
Yeah, this looks to be caused by the header experiment [described here](https://changes.tumblr.com/post/726375529346973696/tuesday-august-22nd-2023). It's probably a slight CSS change; I'll see if I can figure it out sometime this week.

**Comment by AprilSylph** [comment]
If you click in the blank space next to the source name, or the timestamp under it, it goes to the original post. There is nothing missing here.

**Comment by inklesspen** [comment]
Respectfully, there is something missing: clicking the timestamp goes to `https://www.tumblr.com/someblogname/1234567`, instead of `https://someblogname.tumblr.com/post/1234567`

Being able to get links to the blog post instead of the dashboard view is important for folks who want to give out links that work for people who aren't signed into Tumblr, or who want to still believe that this is a microblogging site.

**Comment by inklesspen** [comment]
There are three changes in the recent header experiment:

* The class `reblogRedesignEnabled` is added to the article, header, and many divs/spans inside the header
* The posting blog name no longer has the `attributionHeaderText` class (or indeed any useful class), but the nested `a` tag has the class `blogLink` instead  (this breaks the `postAttributionLink` restoration in the tweak)
* If the reblogged-from post is one of the posts in the reblog trail (that is, the reblogged-from post added visible content), the reblogged-from blog name (with class `rebloggedFromName`, which is used for the `reblogAttributionLink` restoration) is omitted from the HTML

I think the tweak should definitely be updated to restore the link on the posting blog name, since that is the purpose of the tweak.

Re-adding the reblogged-from blog name is more debatable, since we would be adding DOM nodes back into the header. However, I think most users of this tweak _would_ want this.

**Comment by marcustyphoon** [comment]
> Respectfully, there is something missing: clicking the timestamp goes to `https://www.tumblr.com/someblogname/1234567`, instead of `https://someblogname.tumblr.com/post/1234567`
> 
> Being able to get links to the blog post instead of the dashboard view is important for folks who want to give out links that work for people who aren't signed into Tumblr, or who want to still believe that this is a microblogging site.

Those links do work when logged out.

But yes, those are indeed missing... if the user has the Open in Tabs extension enabled, as that's the point of it.

**Comment by marcustyphoon** [comment]
> I think the tweak should definitely be updated to restore the link on the posting blog name, since that is the purpose of the tweak.

Ah, yep.

> If the reblogged-from post is one of the posts in the reblog trail (that is, the reblogged-from post added visible content), the reblogged-from blog name (with class rebloggedFromName, which is used for the reblogAttributionLink restoration) is omitted from the HTML

That does mean that there is a way to get to the previous trail item: click the header of that visible content. Indeed, one can debate the utility there.

**Comment by inklesspen** [comment]
> But yes, those are indeed missing... if the user has the Open in Tabs extension enabled, as that's the point of it.

I'm sorry, perhaps I'm misunderstanding you, but disabling Open in Tabs does not appear to make any difference on the post URLs in the headers.

> That does mean that there is a way to get to the previous trail item: click the header of that visible content. Indeed, one can debate the utility there.

That's true. However, I vastly prefer a link to the blog view (`https://someblogname.tumblr.com/post/1234567`) instead of the dashboard view (`https://www.tumblr.com/someblogname/1234567`). Further, it is strange and disconcerting that sometimes the reblogged-from link is in the header and sometimes it is not.

**Comment by marcustyphoon** [comment]
> I'm sorry, perhaps I'm misunderstanding you

Oh, my bad: Open in Tabs *should* do this, but as per #751 it is mostly broken right now.

>  I vastly prefer a link to the blog view

We should indeed thus update Open in Tabs so you can get this! I just meant to say that it would be fixed under that rather than in the "restore attribution" tweak; sorry for the confusion.

---

@AprilSylph note that reblog redesign aside, this is broken for presumably the same reason as #1237.
