### ISSUE TITLE
Seen Posts isn't consistently dimming or hiding seen posts

### ISSUE THREAD

**Issue by ChangelingRain** [AprilSylph/XKit-Rewritten#1245]
### Platform

Windows 10

### Browser

108.0.2 (32-bit)

### Addon version

v0.22.1 (beta)

### Details

as title; open dashboard, see a post, reload the page, the post you saw isn't dimmed(or hidden with the 'hide seen posts' option on)

**Comment by marcustyphoon** [comment]
Shoot. I put a bunch of fixes in to Seen Posts in v0.22.1, which you've said you have. I haven't been able to reproduce this in some brief testing so I'm not currently sure what's causing it; if anyone can help or provide further details about things that do/don't cause it, that would be awesome.

UNLESS: Is this fixed by opening a new Tumblr tab? It's slightly possible, but pretty unlikely, that you were just updated to v0.22.1 and the fixes haven't loaded yet.

**Comment by ChangelingRain** [comment]
I haven't had this issue for a while so I think it got fixed at some point! may it never come back.
