### ISSUE TITLE
Legacy post edit continue button not responding.

### ISSUE THREAD

**Issue by AcePhoenix32** [AprilSylph/XKit-Rewritten#1271]
### Platform

Windows 10

### Browser

Chrome 64 GB

### Addon version

v0.22.1

### Details

Can't edit reply on tumblr post

Note: Legacy post
This thread was originally created, or at some point was edited, using the legacy post editor or a previous XKit version.

On these threads, Trim Reblogs may work normally, have no effect, or require a repeat of the trim action to completely remove the desired trail items.

When pressing the continue button, there is no response

**Comment by enchanted-sword** [comment]
Could be caused by Tumblr removing the legacy editor as of today.

**Comment by marcustyphoon** [comment]
I don't think that would be related, since we're using entirely NPF API calls and the failure is on a fetch. Not impossible, though?

**Comment by AprilSylph** [comment]
It's not broken across the board; I can still continue to trimming a legacy Link post on my test blog.

**Comment by marcustyphoon** [comment]
Yeah, same. We need to add error handling to the API request so there's some indication what's happening (#1272)—this could, for all we can tell without seeing the javascript console output, be a bug in e.g. `createPreviewItem` that only happens on that particular post structure rather than the API call 404ing.
