### ISSUE TITLE
Quick Tags: Add different asker tags for different blogs?

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1275]
### Concept

Would it be possible to have the Quick Tags "Automatically tag asker when answering" and "Answer tag" features add different tags depending on which blog is answering the ask? E.g. tagging askers and adding a certain asker tag on one sideblog and not tagging askers and adding a different asker tag on a different sideblog.

**Comment by AprilSylph** [comment]
Not with the current framework. The preferences are completely account- and blog-agnostic, with I think just the one exception in the case of Quick Reblog being able to store the last-used blog per account, which itself only really works because it's not really a "preference", i.e. is set from outside the control panel. (We also hash what we commit to storage in that case for the sake of keeping config files non-identifying.)
