### ISSUE TITLE
Separate queue and reblog tags from Quick Reblogs

### ISSUE THREAD

**Issue by moonflowcr** [AprilSylph/XKit-Rewritten#1457]
### Concept

As someone who doesn't need to use Quick Reblogs on Web but wants to use a queue tag, I think it'd be a great idea to separate those into two different extensions. What I suggest is making a new one to set a customized queue/reblog tag, and if possible, with the ability to set a different one for each sideblog or select for which blogs we'd use that tag.

**Comment by marcustyphoon** [comment]
I think that would be less splitting Quick Tags into two features and more adding an entirely separate feature, since Quick Tags only has automatic tagging features implemented within it; having automatic tagging outside of it would require entirely new code.

Also, not sure we have the ability to do this in some cases, at least easily. Tumblr's built in quick queue buttons don't open the post form, for example, and modern web extension APIs remove (that I can think of off the top of my head) the easiest way to intercept and modify the queue action in that case.
