### ISSUE TITLE
Changes/Shop/etc. links carousel appearing on dash at halfway point (No recommended and tweaks are on) 

### ISSUE THREAD

**Issue by AcePhoenix32** [AprilSylph/XKit-Rewritten#1489]
### Platform

Windows 10

### Browser

Chrome 64 bit

### Addon version

v.0.23.6

### Details

Changes/Shop/etc. links carousel appearing on dash at halfway point (No recommended and tweaks - Turn the Changes/Shop/etc. links carousel into a separating line' are on),

**Comment by marcustyphoon** [comment]
Additional information from Discord, for developer reference:

- Endless scrolling is enabled.
- Mutual Checker's "only show posts from mutuals" works (so this is not caused by the `data-timeline-id` migration)
- Carousel title is "Random Tour Spots." I don't think that's a carousel title I've encountered, so this is probably a slightly different element, which means I would need to find one to write code to target it.
