### ISSUE TITLE
Collapsed Queue not working on Drafts page

### ISSUE THREAD

**Issue by arcanetrivia** [AprilSylph/XKit-Rewritten#1529]
### Platform

Windows 10

### Browser

Firefox 127.0.2

### Addon version

0.23.6

### Details

A few days ago I noticed that Collapsed Queue is no longer collapsing posts on the Drafts page. It's still working on the Queue page. Screenshot is mainly to prove that "Run on the drafts page" is in fact checked:

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/68124115/ca00dbfb-d78a-4b51-a833-5279a7f5c442)

(I looked for both open and closed issues regarding this, but knowing me, I still managed to miss it 😅 I saw #1502 but I don't know enough to know if that's related...)

**Comment by AprilSylph** [comment]
this is another TimelineV2 migration we need to update our timeline-matching code for. should be simple enough.

unfortunately, Mozilla is taking a _while_ to review updates - it's been one week since we released v1.0.0, but it's still not approved for Firefox. so, expect the following process for this fix:
1. we fix the issue in the codebase (closing this issue)
2. we wait for Mozilla to approve the previous update (no idea how long this will take! it usually doesn't take 7+ days!)
3. we release a new update with the fix for this issue (likely a v1.0.1; feel free to watch the repository for new releases to be notified of this)
4. we wait for Mozilla to approve _that_ update ( :confounded: )

**Comment by marcustyphoon** [comment]
I wonder if we keep our place in the Mozilla review queue if we release a new version before the current version gets reviewed...

**Comment by AprilSylph** [comment]
I'm certain that if we release a new version, then both versions are still pending review - I've definitely seen that before on the addon dashboard.

What I'm not certain of is whether Mozilla is guaranteed to review the previous version first. For all I know, they could approve v1.0.1 and then approve v1.0.0, and I don't know which version ends up as the "latest" version in that situation.

**Comment by marcustyphoon** [comment]
I mean—surely Mozilla understands semver. Unless extension versions are just arbitrary strings... okay, I guess I wouldn't be entirely surprised.

**Comment by Revolos55** [comment]
Any moment on this issue? Like, of the hypothetical 4-step process, what step are we on?

**Comment by marcustyphoon** [comment]
We've just completed step 3!

**Comment by arcanetrivia** [comment]
I've noticed a quirk about this on the Drafts page (only, again; works as expected on the Queue): If I click the pencil to edit a post, then either save the draft or close the editor and discard the changes (whether or not I actually made any), that individual post is no longer collapsed. It will be again if I refresh the page, but it's not returned to the collapsed state immediately after editing.

**Comment by marcustyphoon** [comment]
Oh, that's a separate issue, but I can fix that!
