### ISSUE TITLE
"hide filtered posts entirely" not working

### ISSUE THREAD

**Issue by irbcallmefynn** [AprilSylph/XKit-Rewritten#1555]
### Platform

Windows 10

### Browser

Firefox 128.0.3 (64-bit)

### Addon version

v1.0.1

### Details

I have the option "Hide Filtered Posts Entirely" enabled, but it isn't hiding posts that contain filtered tags.
![Screenshot 2024-07-28 144441](https://github.com/user-attachments/assets/353566d5-e9c6-4fbd-92e0-aa5b0501c120)
sometimes when I clear the website cache, it will begin working again, but will then break again, usually after refreshing the page.

**Comment by marcustyphoon** [comment]
Do you use any other XKit functionality? When this happens, are other functions working or is everything not working? (The tweak in question is one of our simpler ones and I haven't managed to reproduce the failure, so I'm trying to figure out if your issue is with something in it specifically or with the entire extension.)

**Comment by irbcallmefynn** [comment]
Generally everything else seems to work fine when it stops working. There's also no consistency in when it occurs for me. It hasn't happened to me since I made this report, so maybe it was just my computer that day?
