### ISSUE TITLE
Quick report button

### ISSUE THREAD

**Issue by Charlignon** [AprilSylph/XKit-Rewritten#1615]
### Concept

Porn bots spamming in popular tags is not a new thing. I usually do my best to report them when I can. But on web, this is a terrible experience : it takes 5 clicks/actions to Meatball menu > Report > Select reason > Confirm > Close tab
When you report dozens of posts at once, it is very tiresome

## Proposition
New addon that adds a menu item to quickly report a post for spam (similar to [PostBlock](https://github.com/AprilSylph/XKit-Rewritten/wiki/Features#postblock))
Two configurable settings : skip confirm, and auto block 

## Acknowledgement
I could jump right into coding, but I have found this old similar issue #980 , so I am not sure if this would be desirable or not

**Comment by AprilSylph** [comment]
I'd be wary of hacking in a new way to report posts, mainly for the reason that Tumblr's reporting system [is already itself filled with spam reports](https://www.tumblr.com/echo/753257362184421376?source=share). I don't want XKit to exacerbate that problem. Just because we could trust each other with this theoretical feature doesn't mean we can trust everyone who can download a Chrome extension or Firefox add-on.

**Comment by Charlignon** [comment]
Thought so ! Thank you for your wise input :)
