### ISSUE TITLE
Clicking on a blog results in a black screen.

### ISSUE THREAD

**Issue by OldCrow44** [AprilSylph/XKit-Rewritten#1640]
### Platform

windows 11

### Browser

firefox 131.0.3 (64-bit)

### Addon version

Version 1.0.3

### Details

When clicking on a specific tumblr blog, the screen loads the blog and then proceeds into a black screen. When I hit the back or forward buttons, despite moving to other screens, the display stays black until refreshed. 

https://github.com/user-attachments/assets/c587065a-1d12-4dd9-a996-daf16887f85a

**Comment by OldCrow44** [comment]
I'm sorry if this is sparse, I used to work a job doing bug reporting, but i'm a but rusty since that was in 2017-2018 ish, I hope the video is able to better articulate the issue, as i'm also unsure if it's an XKit bug, or a tumblr bug, or just firefox being firefox. If needed, I can try to replicate in other browsers.

**Comment by marcustyphoon** [comment]
Thanks for the video! If I had to guess, one of your extensions is editing the page in a way that crashes the Tumblr render code, which we're pretty careful to avoid, but only because we know how it works. I see you have a fair number of other extensions, which would be my first suspicion; does it happen if you temporarily turn those off (`about:addons`) and refresh? You may have to do a bit of a binary search to figure out which one it is. If it's actually XKit Rewritten, of course, I'll take a look.
