### ISSUE TITLE
Weird Bugs and issues

### ISSUE THREAD

**Issue by NovaxStarr** [AprilSylph/XKit-Rewritten#1656]
### Platform

windows 10

### Browser

firefox 133.0 (64 bit)

### Addon version

V1.0.4

### Details

I believe it's the xkit extension causing me problems, because I have done a lot of trouble shooting with all of my extensions and updated everything, so I'm not sure what else it could be.
My tumblr page has not been working correctly, I contacted their support and they were of no help. Here are my issues:

1. I have to reblog/queue/schedule things twice, because the first time never works and I get a weird error message.
2. My activity/ messages and dashboard numbers do not refresh and have been stuck on the same numbers, for like a week now.
3. I cannot reply/comment on posts at all.
4. Autosave does not work on any posts I create and does not save to my drafts.

I'll attach screenshots of the error messages. I don't know if all of this is your extension, but I don't know what othe extension it could be, and tumblr support is not helping me.
![tumblr bugs](https://github.com/user-attachments/assets/651ebcf9-d21c-4e8e-b9a5-99a256972eee)

**Comment by AprilSylph** [comment]
It looks like this is another case of #206. tl;dr: your Firefox profile is broken and I have no idea how to fix it, the only method of unbreaking your Firefox+Tumblr experience is to start a new Firefox profile and transfer everything over.

FWIW this isn't caused by XKit Rewritten, the stuck notifications thing has happened to a friend of mine who did not have the addon installed.
