### ISSUE TITLE
Quick Reblog: Option to remember last selected blog

### ISSUE THREAD

**Issue by alecxvs** [AprilSylph/XKit-Rewritten#220]
Quick Reblog does not currently remember the last selected blog. In the case where almost all reblogs are not made to the primary blog, selecting the correct blog every time becomes tedious.

**Comment by Circeus** [comment]
Yes, this was the first thing I noticed, as I am in that situation.

**Comment by amconners** [comment]
Since the second part of #180 is almost this same request and was closed, I'd like to suggest having a setting in the Quick Reblog options that lets the user choose their default blog as an alternative. This keeps the current default behavior _and_ adds a way to get the desired functionality with a one-time setting change for users who primarily use a sideblog.

**Comment by AprilSylph** [comment]
XKit Rewritten's settings page cannot communicate with Tumblr, so setting a different blog as your default outright is impossible. This is also what is preventing Mutual Checker from having a setting to check sideblogs instead of your primary blog.

A setting to simply not reset the blog field of the Quick Reblog popup is something I'm not ruling out. I mostly closed that issue for the keyboard shortcut suggestion; maybe I need to put in the `CONTRIBUTING` doc that new issues should only address one thing at a time.
