### ISSUE TITLE
[Firefox addon] Endless reload of Tumblr cookie consent page when not logged in yet

### ISSUE THREAD

**Issue by 130G** [AprilSylph/XKit-Rewritten#242]
Going on the [log in page of Tumblr](https://tumblr.com/login) with the addon enabled, triggers Tumblr to load the cookie consent page endlessly.

When I disabled the addon, it worked again and showed the log in page.

**Comment by AprilSylph** [comment]
I'll investigate this, but next time please use the provided **Bug report** issue template. It asks for the information it does for a reason.

**Comment by Ikeruga** [comment]
- The browser I'm using is: 
Vivaldi and Microsoft Edge (Chromium)
- My browser version is: 
Vivaldi | 4.1.2369.21 (Stable channel) (64-bit)
Edge (Chromium) | Version 93.0.961.47 (Official build) (64-bit)
- My XKit Rewritten version is: 
0.8.0
---
I'm running into the same issue. I'm accessing from a European IP address, if that matters because of GDPR cookie things. If I enable Mutual Checker or Quick Reblog I can reproduce it easily. Disabling Mutual Checker and Quick Reblog makes it work fine. If I can offer any other info let me know!
