### ISSUE TITLE
Option to hide "You're caught up." banner entirely?

### ISSUE THREAD

**Issue by amconners** [AprilSylph/XKit-Rewritten#251]
AccessKit lets you de-animate the banner, but I can't see any way to hide it and its suggestions entirely. Perhaps an option under No Recommended would fit this option.

**Comment by AprilSylph** [comment]
The way I'd personally like to implement this is a little more complex than simply hiding the carousel, since the header for it is indisputably useful; I'd like to be able to modify the header text, across all languages, to remove the "Check these out:" part. The all languages part is difficult, but I think it's worth doing.

**Comment by marcustyphoon** [comment]
It looks like the grammar in some of these will make it quite difficult indeed:
```
Alles gesehen? Wir haben noch viel mehr:
Seen everything? We have a lot more:
```
```
Acha que já viu de tudo? Que nada. Temos mais para você:
Do you think you've seen it all? That's nothing. We have more for you:
```
```
Ti vedo interessato. Dai un'occhiata a questi:
I see you're interested. Check out these: 
```
https://gist.github.com/marcustyphoon/e92c3fcac661fe8b6582fa0c9f01ac09

**Comment by AprilSylph** [comment]
Yeah, looks like a plain separator line is the best (see: easiest) solution.
