### ISSUE TITLE
Quick Tags input strings

### ISSUE THREAD

**Issue by kaazrut** [AprilSylph/XKit-Rewritten#267]
- The browser I'm using is: Firefox
- My browser version is: 92.0 (64-bit)
- My XKit Rewritten version is: 0.8.0

---
This might be a code change that you're aware of, but in case it's not:
Under the Quick Tags option, I've run into unexpected behavior when trying to define a Tag Bundle. When entering the tags, sometimes, when I hit Enter or 'Add Bundle', the two form fields clear, but nothing appears in the list of Tag Bundles.

I tested the behavior by trying the following:

-spaced tags ("test test, testing") 
Result: works

- two spaced tags ("test test, testing 1")
Result: works

-three spaced tags ("testing 1, testing 2, testing 3")
Result: works

-two spaces per tag("testing 1 2, testing 3 4")
Result: fail

-two spaces one tag, no spaces second tag ("test 1 2, testing")
Result: fail

-hypens ("testing-one-and, two-and-three")
Result: works

I had installed a previous version of XKit Rewritten on a different machine, running an older version of Firefox. There, I had been able to successfully create a Tag Bundle in the same form as the "two spaces per tag" testcase.

Edit: additionally, when I have a tag bundle on the list, if I chose to Edit an existing bundle, I apparently can input arbitrary strings into the tag field.

Again, I don't know if this was an intentional code change or if Tumblr did something screwy, but in case it's an actual bug, well, here's the bug report and the set of testcases I ran through.

**Comment by AprilSylph** [comment]
Using the Enter key does seem to behaving oddly. I can't reproduce when using the "Add bundle" button, though. Probably something to do with the way the form element is set up.

> Edit: additionally, when I have a tag bundle on the list, if I chose to Edit an existing bundle, I apparently can input arbitrary strings into the tag field.

This is the intended behaviour. Both fields when creating a tag bundle should also accept any input; they're stored as strings, and the commas are only used to split apart the tag list when you actually apply them to a post.

I'll take a look at it when I can. I haven't touched the Quick Tags preferences code at all since v0.3.3 so it's probably due some internal renovation.
