### ISSUE TITLE
Custome time format for Timestamps

### ISSUE THREAD

**Issue by piotrmil** [AprilSylph/XKit-Rewritten#326]
### Concept

Quite simple thing - in New Xkit, you could add your own time format. You only gave three options. The ISO one, while the most correct, is also very unreadable. We just need to be able to see day before month. all I'm saying ;)

**Comment by AprilSylph** [comment]
Timestamps will not receive any additional options, as it is slated for removal in favour of Tumblr's upcoming native version.

[Tumblr Hack Day, June 2021](https://engineering.tumblr.com/post/654257188393697280/tumblr-hack-day-june-2021-edition)
![image](https://64.media.tumblr.com/22e5dcb8de6870d1db8fcf5640922736/e9e99b92c071f252-95/s1280x1920/ecaa440fba752642348c7e2daec84df33b8fa41a.png)

[Changes on Tumblr @ September 10th, 2021](https://changes.tumblr.com/post/661959453172793344/friday-september-10th-2021)
> We’re still working on the option to see Timestamps on posts, reblogs, and notes. This’ll be a setting on web to start, eventually making its way to the mobile apps. Third party API users may get to see these timestamps even earlier.

While these dates may seem like the feature is far off, I received the toggle yesterday as part of early feedback gathering.

I will be considering a feature that allows reformatting native timestamps, perhaps with a locale option. Timestamps currently matches the dashboard's language (meaning `en-US` in English) because its set of options is supposed to be simple, but a reformatter would already be complex enough to justify the addition of a locale selector.
