### ISSUE TITLE
Quick reblog issue

### ISSUE THREAD

**Issue by XargonDragon** [AprilSylph/XKit-Rewritten#357]
### Platform

Windows 10 Version 20H2

### Browser

Chrome Version 96.0.4664.93 (Official Build) (64-bit)

### Addon version

0.10.1

### Details

When I use the Quick Reblog module and add something to my queue, xkit instead sends the post to my drafts, and when in my drafts if I attempt to send a post to my queue from there it vanishes completely.

**Comment by AprilSylph** [comment]
This is Tumblr behaviour, not a bug with Quick Reblog. If a queued post fails to post for any reason (and potentially, if your queue is full and you try to add a new post there), it will end up in your drafts.

I had a queued post fail to publish for unknown reasons last week, it ended up in my drafts, and attempting to queue it from my drafts made it disappear. The fact it disappears is undoubtedly a Tumblr bug, as XKit has nothing to do with that process at all.

Since Quick Reblog makes nigh-identical requests when reblogging as the beta post editor, using the beta post editor to reproduce this issue (assuming it's happening consistently) should be easy, at which point you should [contact Tumblr support](https://www.tumblr.com/support) to report it.

**Comment by XargonDragon** [comment]
Thank you so much for the quick response and all the help!
