### ISSUE TITLE
Seen Posts no longer dimming

### ISSUE THREAD

**Issue by hollowsbest** [AprilSylph/XKit-Rewritten#439]
### Platform

Windows 10 64-bit v10.0.19042

### Browser

Opera GX v82.0.4227.50

### Addon version

v0.14.4

### Details

It's turned on, but posts are no longer dimming as I reload after I see them. Last dimmed post was from hours ago down my dash.

**Comment by AprilSylph** [comment]
Confirmed. Seen Posts is unable to properly process posts upon pageload.

**Comment by hollowsbest** [comment]
no problem! glad it seemed an easy find, and hopefully an easy enough fix : )

**Comment by AprilSylph** [comment]
This is now fixed in XKit Rewritten v0.14.5; I'm not entirely familiar with the force-update process for extensions installed in Opera via the Chrome Web Store, but you should automatically receive it within the next day either way.

Wikipedia doesn't seem to have too detailed information on Opera releases, but assuming Opera GX uses the same version number as the Opera version it's based on, you should be fine to receive this. A performance optimisation meant I had to bump the minimum Chrome version to 88, which is what Opera 74 is based on.
