### ISSUE TITLE
Incorporate CSS Dark Theme?

### ISSUE THREAD

**Issue by jkopczyn** [AprilSylph/XKit-Rewritten#445]
### Concept

I maintain a [Stylus style][1] for the Tumblr dash, a messy but adequate dark theme. It needs frequent small updates and the stylesheet is ugly as all hell, because of the obfuscated class names, but it works. Would it be possible to incorporate that into Xkit?

A bigger feature might be 'Stylus integration' where an Xkit feature saves one or more stylesheet references and imports them on each device, which would have uses beyond this one. Probably considerably more work, though.

[1]: https://userstyles.world/style/1159/tumblr-dark-dashboard

**Comment by marcustyphoon** [comment]
I think this is more of a feature request, Palettes for Tumblr! https://github.com/AprilSylph/Palettes-for-Tumblr

It doesn't currently have support for user-created palettes, but I believe it's something she intends to add eventually or has at least considered adding. Right now it wouldn't be of use to you as far as dark mode goes, since its dark mode is just the one built into Tumblr.

(Out of curiosity: I can't quite tell if your style is intended as a conversion from Tumblr's regular palette to dark mode or an increase in the contrast for Tumblr's dark mode! I assume the latter?)

**Comment by AprilSylph** [comment]
Palettes for Tumblr will support custom palettes soon. The code is there, I just need to improve the UX before releasing it.

Full dashboard restyles or "themes" are out of scope for either addon.
