### ISSUE TITLE
NotificationBlock completely broken

### ISSUE THREAD

**Issue by sailorcardassia** [AprilSylph/XKit-Rewritten#491]
### Platform

macOSX 10.13.1

### Browser

Chrome 98.0.4758.102 (Official Build) (x86_64)

### Addon version

no idea where to find this info

### Details

I have the NotificationBlock feature enabled on my xkit that I'm using on my browser for Tumblr, but when I click it for a post it does nothing. It still appears in my Activity tab with no change. I'm finding this really frustrating as I've had some posts go viral on Tumblr recently where I'd really like to be able to block notifications entirely. I'm surprised not to see this reported on here, as I have friends who also have this issue. Please let me know how I can fix this.

**Comment by marcustyphoon** [comment]
> when I click it for a post it does nothing

Do you receive a confirmation dialogue when you click the notificationblock menu item but then don't observe that post's notes being hidden, or does the button do nothing when clicked?

<image width="400" src="https://user-images.githubusercontent.com/8336245/155276859-0de9fe2a-9b4b-4b0b-b0f8-5e6b008f89a6.png">

**Comment by sailorcardassia** [comment]
Yeah, I get the "block this post's notification" confirmation when I hit it, but then it's still on the Activity page.

**Comment by marcustyphoon** [comment]
Hm, interesting!

If you right click one of the notification entries on the activity page (one that should be hidden, I suppose) and click "inspect element," do you see a line containing `data-target-post-id` in the resulting developer tools window, in or just above the selected line? (NotificationBlock adds these to the page code so it can tell what post a notification entry is about; if it's missing or incorrect, that part must be broken, while if it's there, something else must be.)

<img width="1680" src="https://user-images.githubusercontent.com/8336245/155284483-0ad94b32-501f-4a34-bb09-b344c274a25f.png">

<img width="1680" src="https://user-images.githubusercontent.com/8336245/155284468-ebbc18c3-4bfe-4439-9cd9-2ae7c303e0ce.png">

**Comment by AprilSylph** [comment]
Are you trying to block the notifications for the original post? If you reblogged it yourself and block that reblog's notifications, it won't block the original post's notifications.

**Comment by AprilSylph** [comment]
Unable to reproduce on Chrome Version 100.0.4892.0 (Official Build) dev (arm64)

**Comment by AprilSylph** [comment]
> Are you trying to block the notifications for the original post? If you reblogged it yourself and block that reblog's notifications, it won't block the original post's notifications.

We had a discussion about this in #492, and we concluded that this behaviour is confusing without being useful. Starting in v0.15.3, NotificationBlock will now work on a root ID basis (like PostBlock already did), so there shouldn't be any distinction between blocking a reblog's notifications and the original post's notifications. The trade-off is that any blocks you previously made for notifications on reblogged posts won't be respected; you'll need to block their notifications again.

Google just approved the update as I'm typing this. Update to v0.15.3 via `chrome://extensions` -> Developer mode -> Update, reload any Tumblr tabs you have open, then let me know if your issue is fixed. If you have posts which have "Unblock notifications" buttons but have visible notifications on your activity page, I would be very surprised.
