### ISSUE TITLE
Show Originals: Peepr option does not always detect Peepr beta

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#499]
### Platform

MacOS 10.14.6

### Browser

Edge 98

### Addon version

0.14.6

### Details

Show Originals' option to run in the blog view drawer works with the new beta version if it is opened by clicking within the Tumblr UI, as it opens in a glass container over the screen just like old Peepr in that case, but it does not work if you directly navigate to `https://www.tumblr.com/blog/view/blogname` with the beta, as the blog view container is directly embedded as the main page content now.

**Comment by AprilSylph** [comment]
A simple option for detecting if any element is in Peepr could be to check if a Peepr-specific CSS variable is set (since CSS variables apply to descendants too):
```js
const isInPeepr = element => getComputedStyle(element).getPropertyValue('--blog-title-color') !== '';
```

You could also check the page for the `isPeeprShowing` classname, but that would be async due to relying on the CSS map.

For Show Originals specifically, it definitely makes sense to exclude the in-channel views from being actioned on. But for other features, I'm also thinking that the new blog view makes the distinction less important; I'm going to have a look at what features use `noPeepr` and see if they really need to.

**Comment by marcustyphoon** [comment]
> check if a Peepr-specific CSS variable is set

Aha, clever! 

> You could also check the page for the isPeeprShowing classname

Checking the whole page for anything doesn't work by itself because you can open Peepr over the... in-channel views, which we're using to refer to e.g. your own blogs, your likes, etc, right?

**Comment by AprilSylph** [comment]
Ah, right.

And I'm using "in-channel" to refer to `/blog/<blogname>/*`, so not your likes.
