### ISSUE TITLE
Post Block: Meatball menu option to block posts not displaying.

### ISSUE THREAD

**Issue by fleurite** [AprilSylph/XKit-Rewritten#545]
### Platform

Windows 10 Home version 21H1

### Browser

Firefox 99.0.0.8124

### Addon version

v0.19.1

### Details

Hello, I found today that the meatball menu that usually displays the option to block a post is not displaying it. I have endless scrolling disabled on Tumblr and after toggling the extension on and off, refreshing the tab, restarting Firefox, and making sure both the browser and add-on are up to date, I am still experiencing this problem.

As far as current functionality, the add-on options still allow me to unblock posts.

I have attached a screenshot to help illustrate the issue. Please note that uBlock Origin is disabled, which eliminates the possibility that I accidentally hid it by blocking the corresponding element.

![Screenshot 2022-04-08 110346](https://user-images.githubusercontent.com/95893576/162497085-cf0d45e5-6028-479e-a05c-31bbf1cd3d0d.png)

**Comment by marcustyphoon** [comment]
Thanks for the report! Confirmed. My 30-seconds-of-investigation guess is that Tumblr has switched to using a React `Portal` to render the meatball menu, so the code we use to find it needs to be updated.

**Comment by AprilSylph** [comment]
This looks annoying. The DOM position was how we ensured we only actioned on posts' meatball menus and not e.g. menus for blogs or replies.

**Comment by AprilSylph** [comment]
I guess we could test each meatball menu individually to see if it has a post permalink.

**Comment by marcustyphoon** [comment]
_Now you're thinking with portals!*_
_*Spoiler alert: it's just an general inconvenience._

Anyways, I think we will have to do so anyway, essentially; the buttons will also need to know what post they are supposed to be actioning on, and that was DOM position based as well.

**Comment by marcustyphoon** [comment]
(Correction to my previous comment: perhaps not. The React hierarchy is still in place as normal, so traversing up the React tree may be an easier way to identify a popup's data than parsing its DOM data.)

**Comment by marcustyphoon** [comment]
Okay, I have a few notes here:

1. You can call the current implementation of timelineObject on a meatball menu, completely unmodified. It traverses the React structure and grabs the post data just fine. This could provide all necessary data to the onclick handlers of the three scripts that use meatball menus with minimal extra lines of code (I think; didn't fully check yet). `postFilter` could provide `timelineObject` data instead of a `timelineElement` DOM reference. This would be limiting if future meatball menu functionality cares about things on the actual post DOM.

2. Can posts show up more than once on a page? I think yes. Handling this case aside, the previous method can find the post id, the post in question can be found using querySelector, and we can action on the found postElement as normal. 

3. To implement the filter that only actions on post meatball menu without actually checking the menu contents, we could traverse the React tree until we get to the first `header` element, then test that header's DOM position as the current code does. I think this is unambiguous. Unfortunately, this traversal is done in an injected function, and we can't send DOM references back from inject(), so the filtering code would have to be in the inject as well.

4. To solve the ambiguity in (2) in a convoluted way, (3) could add a randomly generated data attribute to the unambiguously correct post that it finds, or something, but this is rather silly.

---

~~3. From adding logging inside `unburyTimelineObject`, it looks doable to traverse the React tree only until you go through the portal, though this is dependent on Tumblr's code (look for `usePortals: true` in props,  then look for `typeof elementType === 'string'` in fiber and return `fiber.stateNode`, for example). This spits you out where the meatballs menu used to be attached, so the code would work as before, including the menu filtering selector. Unfortunately, this traversal is done in an injected function, and we can't send DOM references back from inject(), so the filtering code would have to be in the inject as well.~~
