### ISSUE TITLE
Tweak to go back to original notes

### ISSUE THREAD

**Issue by BarryAllen2024** [AprilSylph/XKit-Rewritten#576]
### Concept

Tweak to change how the notes look now to how they looked originally, with the full number and notes next to it

**Comment by marcustyphoon** [comment]
I assume this is about the new footer with user-specific buttons in a separate row above the current one and with note counts listed as e.g. "1.8k" instead of "1835."

I believe this is a test by Tumblr staff, as I don't have it on either of my accounts at the moment. Please give polite, specific feedback on why you prefer the details you prefer at https://www.tumblr.com/support!

**Comment by cateyedsnake** [comment]
I'm pretty sure they mean the 1.8k=1835 thing. I fully agree, it is so ugly.

**Comment by AprilSylph** [comment]
I closed this because Tumblr had reverted that test, but it looks like there's a new one now.
