### ISSUE TITLE
No Recommended: Broken carousel hiding 

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#616]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 101.0.1210.53

### Addon version

v0.19.5

### Details

Tumblr's changes to GIF loading (detailed in #615) toggle the `visibility` css attribute on image elements to switch between static and an animated versions of GIFs.

This interferes with the changes in #282, as the Tumblr-set `visibility: visible` on GIFs within carousels overrides the `visibility: hidden` used to hide the carousels.

(Am I supposed to add the help wanted tag to issues like this?)

**Comment by AprilSylph** [comment]
> (Am I supposed to add the help wanted tag to issues like this?)

If you (a project collaborator) can confirm that the bug exists, is caused by XKit Rewritten (i.e. is not an issue without it installed), and don't want to assign yourself to the issue, then yes, add the help wanted label.

An issue is considered unconfirmed if it does not have **help wanted**, **wontfix**, or an assignee; unconfirmed issues are eligible to be closed for inactivity,
