### ISSUE TITLE
[Quick Reblog] Reblogging Ask Posts uses Inaccurate Confirmation Text

### ISSUE THREAD

**Issue by motackt** [AprilSylph/XKit-Rewritten#74]
- **The browser I'm using is: Brave** 
- **My browser version is: Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)** 
- **My XKit Rewritten version is: v0.0.14 (Alpha)** 

---

When quick reblogging any post that has an Ask (at least that I have tested), the confirmation text is not `Posted to <blogname>`, but is `Answered by <blogname>`.

Why does Quick Reblog have this text when the user is not the person who answered the Ask? Even if the user is OP and **did** answer the Ask, they weren't necessarily answering it again when reblogging.

If this is the intended behaviour, please close this issue.

**Comment by invalidCards** [comment]
As far as I can see, [the extension uses the message that comes back from the Tumblr request as confirmation](https://github.com/AprilSylph/XKit-Rewritten/blob/master/src/scripts/quick_reblog.js#L100), so this'll be a bug in the Tumblr API rather than in XKit Rewritten. I'll leave it up to April if she wants to follow up on this somehow, though.

**Comment by AprilSylph** [comment]
Yeah, this is weird behaviour from Tumblr, but ultimately not a bug with the addon itself. I was going to open an issue in [tumblr/docs](https://github.com/tumblr/docs) to ask about this, but didn't get around to it yet. If you could do so instead (and reference this issue to properly exemplify the problem), that would be a great help!

I agree that the confirmation is confusing; even "Posted to [blog]" when reblogging is technically incorrect in my eyes.
